[package]
name = "nnetwork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.10.1"
anyhow = "1.0.69"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"


